// <auto-generated />
namespace E_SafetyWorkPermit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DepartmentsMasters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DepartmentsMasters));
        
        string IMigrationMetadata.Id
        {
            get { return "201809030748352_DepartmentsMasters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
