//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_SafetyWorkPermit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentRegistration
    {
        public long DepartmentId { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string TokenNo { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
    }
}
